# Generated by Django 5.1.5 on 2026-03-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ftp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="weight_kg",
        ),
        migrations.CreateModel(
            name="FTPHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ftp", models.PositiveIntegerField(help_text="FTP in watts")),
                (
                    "effective_date",
                    models.DateField(help_text="Date this FTP became effective"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual entry"),
                            ("ramp_test", "Ramp test"),
                            ("20min_test", "20-minute test"),
                            ("8min_test", "8-minute test"),
                            ("ai_estimate", "AI estimate"),
                            ("strava_estimate", "Strava estimate"),
                            ("race_result", "Race result"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ftp_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FTP history entry",
                "verbose_name_plural": "FTP history",
                "ordering": ["-effective_date"],
                "unique_together": {("user", "effective_date")},
            },
        ),
        migrations.CreateModel(
            name="WeightHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=1, help_text="Body weight in kg", max_digits=5
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date of this measurement"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weight history entry",
                "verbose_name_plural": "Weight history",
                "ordering": ["-effective_date"],
                "unique_together": {("user", "effective_date")},
            },
        ),
    ]
