# Generated by Django 5.1.5 on 2026-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_ftp_and_weight_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resting_hr",
            field=models.PositiveIntegerField(
                blank=True, help_text="Resting heart rate in bpm", null=True
            ),
        ),
    ]
