# Generated by Django 6.0.3 on 2026-03-04 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("strava", "Strava"),
                            ("garmin", "Garmin"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(help_text="ID in the source system", max_length=200),
                ),
                ("name", models.CharField(max_length=300)),
                ("sport_type", models.CharField(max_length=50)),
                ("start_datetime", models.DateTimeField()),
                ("duration_seconds", models.PositiveIntegerField()),
                ("distance_meters", models.FloatField(blank=True, null=True)),
                ("elevation_gain_meters", models.FloatField(blank=True, null=True)),
                ("average_watts", models.FloatField(blank=True, null=True)),
                ("normalized_power", models.FloatField(blank=True, null=True)),
                ("intensity_factor", models.FloatField(blank=True, null=True)),
                (
                    "tss",
                    models.FloatField(blank=True, help_text="Training Stress Score", null=True),
                ),
                ("average_hr", models.PositiveIntegerField(blank=True, null=True)),
                ("max_hr", models.PositiveIntegerField(blank=True, null=True)),
                ("strava_kudos", models.PositiveIntegerField(blank=True, null=True)),
                ("strava_url", models.URLField(blank=True)),
                (
                    "raw_data",
                    models.JSONField(default=dict, help_text="Full response from source API"),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_datetime"],
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
