# Generated by Django 5.1.5 on 2026-03-16 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="effort_source",
            field=models.CharField(
                blank=True,
                choices=[("strava", "Strava"), ("manual", "Manual")],
                default="",
                help_text="Where the effort rating came from",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="perceived_effort",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Subjective effort rating 1–10",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="power_data",
            field=models.JSONField(
                blank=True,
                help_text='{"time": [0, 1, ...], "watts": [150, 153, ...]}',
                null=True,
            ),
        ),
    ]
