# Generated by Django 5.1.5 on 2026-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0002_effort_and_power_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="hr_data",
            field=models.JSONField(
                blank=True,
                help_text='{"time": [0, 1, ...], "heartrate": [120, 122, ...]}',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="hr_tss",
            field=models.FloatField(
                blank=True,
                help_text="HR-based Training Stress Score (fallback when no power)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="effort_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("strava", "Strava"),
                    ("manual", "Manual"),
                    ("hr_estimate", "HR estimate"),
                ],
                default="",
                help_text="Where the effort rating came from",
                max_length=20,
            ),
        ),
    ]
