# Generated by Django 6.0.3 on 2026-03-04 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("duration_weeks", models.PositiveIntegerField()),
                (
                    "target_hours_per_week_low",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                (
                    "target_hours_per_week_high",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("source_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.trainingplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProgressionScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recovery_score", models.FloatField(default=5.0)),
                ("endurance_score", models.FloatField(default=5.0)),
                ("tempo_score", models.FloatField(default=5.0)),
                ("sweet_spot_score", models.FloatField(default=5.0)),
                ("threshold_score", models.FloatField(default=5.0)),
                ("vo2max_score", models.FloatField(default=5.0)),
                ("anaerobic_score", models.FloatField(default=5.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recovery", "Recovery"),
                            ("endurance", "Endurance"),
                            ("tempo", "Tempo"),
                            ("sweet_spot", "Sweet Spot"),
                            ("threshold", "Threshold"),
                            ("vo2max", "VO2 Max"),
                            ("anaerobic", "Anaerobic"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "progression_score",
                    models.FloatField(
                        help_text="Score threshold (1.0–10.0) at which this rung unlocks. Maps directly to a Rung in progressions.LADDERS."
                    ),
                ),
                (
                    "total_duration_minutes",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "tss_estimate",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("description", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "progression_score"],
                "unique_together": {("category", "progression_score")},
            },
        ),
        migrations.CreateModel(
            name="PlanBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.trainingplan",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.workoutblock",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number", "day_of_week", "order"],
            },
        ),
    ]
