# Generated by Django 5.1.5 on 2026-03-16 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutblock",
            name="intended_effort",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Intended effort 1–10 (auto-set from zone if not overridden)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
